name: Gradle Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Clean, Test, Assemble
        run: ./gradlew clean test integrationTest assemble
      - name: Publish
        env:
          GRAILS_CENTRAL_USERNAME: ${{ secrets.GRAILS_CENTRAL_USERNAME }}
        run: |
          ./gradlew publish_stub
          echo "********* $GRAILS_CENTRAL_USERNAME ********* "
      - name: Docs
        run: ./gradlew docs
      - name: Github Pages
        env:
          GIT_NAME: "Puneet Behl"
          GIT_EMAIL: "behl4485@gmail.com"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REPO_SLUG: ${{ github.repository }}
        run: |
          ./gh-pages-clone.sh
          ./gh-pages-snapshot-docs.sh
