name: Gradle Tasks
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Clean, Test, Assemble
        run: |
          set -e
          rm -rf build
          rm -rf *.zip
          ./gradlew clean test integrationTest assemble
      - name: Publish
        run: ./gradlew publish_stub
      - name: Docs
        run: ./gradlew docs
      - name: Github Credentials
        env:
          GIT_NAME: "Puneet Behl"
          GIT_EMAIL: "behl4485@gmail.com"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
        run: |
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          git config --global credential.helper "store --file=~/.git-credentials"
          echo "https://$GH_TOKEN:@github.com" > ~/.git-credentials
          cat ~./git-credentials
      - name: Github Pages
        run: |
          git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git -b gh-pages gh-pages --single-branch > /dev/null
          ls -al
